export const SOFT_LANGUAGE = [
  /\b(please|kindly|if you could|if you would|would you mind)\b/gi,
  /\b(i would like you to|i want you to|i need you to|i'd like you to)\b/gi,
  /\b(maybe|perhaps|possibly|I think|I believe|I feel like|it seems like)\b/gi,
  /\b(sort of|kind of|just|really|very|actually|basically|essentially|literally|honestly|frankly)\b/gi,
  /\b(as an ai|as a language model|you are an ai|you are a language model)\b/gi,
  /^(can you|could you|will you|would you)\s+/gim,
  /\bI would appreciate it if you could\b/gi,
  /\bdo not hesitate to\b/gi,
  /\b(hello|hi|hey|dear)\b,?\s*/gi,
  /\bthank you( so much| very much)?\s*[.!]?\s*/gi,
  /\bthanks\s*[.!]?\s*/gi,
];

export const VERBOSE_TO_CONCISE = [
  [/\bin order to\b/gi, 'to'],
  [/\bdue to the fact that\b/gi, 'because'],
  [/\bfor the purpose of\b/gi, 'to'],
  [/\bin the event that\b/gi, 'if'],
  [/\bat this point in time\b/gi, 'now'],
  [/\bat the present time\b/gi, 'now'],
  [/\bprior to\b/gi, 'before'],
  [/\bsubsequent to\b/gi, 'after'],
  [/\bin spite of the fact that\b/gi, 'although'],
  [/\bwith regard to\b/gi, 'about'],
  [/\bwith respect to\b/gi, 'about'],
  [/\bin regard to\b/gi, 'about'],
  [/\bpertaining to\b/gi, 'about'],
  [/\bin addition to\b/gi, 'besides'],
  [/\bas a result of\b/gi, 'because of'],
  [/\bby means of\b/gi, 'by'],
  [/\bin the process of\b/gi, 'while'],
  [/\bit is important to note that\b/gi, ''],
  [/\bit should be noted that\b/gi, ''],
  [/\bit is worth mentioning that\b/gi, ''],
  [/\bneedless to say\b/gi, ''],
  [/\bas a matter of fact\b/gi, ''],
  [/\bthe fact that\b/gi, 'that'],
  [/\bin light of\b/gi, 'given'],
  [/\ba large number of\b/gi, 'many'],
  [/\ba significant number of\b/gi, 'many'],
  [/\bthe majority of\b/gi, 'most'],
  [/\bis able to\b/gi, 'can'],
  [/\bhas the ability to\b/gi, 'can'],
  [/\bmake sure that\b/gi, 'ensure'],
  [/\btake into consideration\b/gi, 'consider'],
  [/\btake into account\b/gi, 'consider'],
  [/\bgive an explanation of\b/gi, 'explain'],
  [/\bprovide a description of\b/gi, 'describe'],
  [/\bprovide an explanation of\b/gi, 'explain'],
  [/\bprovide a summary of\b/gi, 'summarize'],
  [/\bprovide a list of\b/gi, 'list'],
  [/\bprovide me with\b/gi, 'give me'],
];

export const REDUNDANT_PATTERNS = [
  /\b(make sure|ensure) (that )?you (are |do )?/gi,
  /\bplease note that\b/gi,
  /\bkeep in mind that\b/gi,
  /\bremember that\b/gi,
  /\bdon't forget to\b/gi,
  /\bI want the (output|result|response|answer) to be\b/gi,
  /\balso,?\s*/gi,
];

export const TASK_NORMALIZATIONS = [
  [/\b(?:creat(?:e|ing)|writ(?:e|ing)|produc(?:e|ing))\s+(?:some\s+)?(?:sort of\s+)?(?:content|something),?\s*(?:like\s+)?(?:maybe\s+)?(?:a\s+)?(?:blog\s*(?:post)?|article)\s*(?:or\s+(?:article|blog(?:\s*post)?)\s*)*(?:or\s+something\s+(?:along\s+those\s+lines|like\s+that)\s*|(?:or\s+something\s*))?(?:whatever\s+works?)?\b/gi, 'write a blog post'],
  [/\b(?:some\s+)?(?:kind\s+of\s+|sort\s+of\s+)?(?:guide|tutorial|walkthrough)\s*(?:or\s+(?:tutorial|guide|walkthrough)\s*)*(?:or\s+whatever(?:\s+you\s+want\s+to\s+call\s+it)?)\s*/gi, 'a guide '],
  [/\b(?:some\s+)?(?:kind\s+of\s+|sort\s+of\s+)?(?:guide|tutorial|walkthrough)\s*(?:or\s+(?:tutorial|guide|walkthrough)\s*)+/gi, 'a guide'],
  [/\b(?:some\s+)?(?:sort\s+of\s+)?(?:content|piece),?\s*(?:like\s+)?(?:maybe\s+)?(?:a\s+)?blog\b/gi, 'a blog post'],
  [/\bor whatever you want to call it\b/gi, ''],
  [/\bwhatever works?\b/gi, ''],
  [/\bif it's not too much trouble\b/gi, ''],
  [/\bif that makes sense\b/gi, ''],
  [/\byou know,?\s*/gi, ''],
  [/\bI almost forgot,?\s*/gi, ''],
  [/\bone more thing,?\s*/gi, ''],
  [/\bthat kind of thing\b/gi, ''],
  [/\byou're the best\b/gi, ''],
  [/\bthanks so much\b/gi, ''],
  [/\bI've been thinking about this for a while\b/gi, ''],
  [/\bI was wondering\b/gi, ''],
  [/\byeah,?\s*/gi, ''],
  [/\bI guess\b/gi, ''],
  [/\bor something(?:\s+like that)?\b/gi, ''],
  [/\balong those lines\b/gi, ''],
  [/\bpretty much\b/gi, ''],
  [/\bnot too (\w+)\s+(?:where|because|but)\s+.+?(?:\.|,|$)/gim, ''],
  [/\bI'm not super strict about .+?(?:\.|,|$)/gim, ''],
  [/\bit's okay if not\b/gi, ''],
  [/\bbut it's okay\b/gi, ''],
  [/\bif possible\b/gi, ''],
  [/\bif you can\b/gi, ''],
  [/\bjust to wrap things up nicely\b/gi, ''],
  [/\bjust something that looks clean\b/gi, ''],
  [/\bI've been thinking about\b/gi, ''],
  [/\bnothing too fancy\b/gi, ''],
  [/\bbefore going all in\b/gi, ''],
  [/\bI've seen a lot of people\b/gi, ''],
  [/\bI'm not sure (?:which one to pick|what to use|about)\b/gi, ''],
  [/\blike a rough\b/gi, 'a'],
];

// Clarity compression: "because it provides flexibility" → "Flexibility as a key driver"
export const CLARITY_COMPRESSIONS = [
  [/\bbecause (?:it |they |this )(?:provides?|offers?|gives?|enables?|allows?) (.+)/gi, (_, thing) => `${thing.replace(/^\w/, c => c.toUpperCase())} as a key driver`],
  [/\b(?:it |they |this )(?:provides?|offers?|gives?) (.+?) (?:for|to) (.+)/gi, (_, what, whom) => `${what.replace(/^\w/, c => c.toUpperCase())} for ${whom}`],
  [/\bthe (?:main |primary |key )?(?:reason|benefit|advantage) (?:is |being )(?:that )?(.+)/gi, (_, reason) => reason.replace(/^\w/, c => c.toUpperCase())],
];
